version: "3.3"

volumes:
  postgres_data:

services:
  myblog:
    build:
      context: .
      dockerfile: ./services/myblog/Dockerfile
    depends_on:
      - db
    restart: always
    expose:
      - 8001
    env_file:
      - ./services/myblog/.docker.myblog.env
    # environment:
    #   - FLASK_APP:${FLASK_APP}

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.docker.postgres.env

  nginx:
    build: ./services/nginx
    ports:
      - 5000:80
    depends_on:
      - myblog
