"""User model added

Revision ID: 320ea402aff7
Revises: b3c553350bbb
Create Date: 2020-11-03 15:58:03.586177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320ea402aff7'
down_revision = 'b3c553350bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    op.drop_table('user')
    # ### end Alembic commands ###
