"""empty message

Revision ID: 35312cef7c94
Revises: 67433e658121
Create Date: 2020-11-04 17:41:11.249948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35312cef7c94'
down_revision = '67433e658121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
