"""empty message

Revision ID: a7b9b1ccc46e
Revises: ad7b5bd5a72a
Create Date: 2020-12-30 11:39:12.439250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b9b1ccc46e'
down_revision = 'ad7b5bd5a72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True, comment='Email used for account confirmation and password reset'))
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=True, comment='Is user email (and so account) confirmed'))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_confirmed')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
