"""main migration

Revision ID: ad7b5bd5a72a
Revises: 
Create Date: 2020-11-19 13:27:31.352997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7b5bd5a72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Username used for authentication'),
    sa.Column('password', sa.Text(), nullable=False, comment='Hashed user password'),
    sa.Column('registered_on', sa.DateTime(), nullable=True, comment='DateTime of registration'),
    sa.Column('admin', sa.Boolean(), nullable=False, comment='Does user has admin privileges'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='If the user is marked for deletion then it should not be valid for authentification'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True, comment='DateTime of post creation'),
    sa.Column('updated_on', sa.DateTime(), nullable=True, comment='DateTime of post update'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='If the post is marked for deletion then it should not be given to the client'),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
