"""empty message

Revision ID: be1679aa8d54
Revises: a7b9b1ccc46e
Create Date: 2020-12-30 11:40:33.690200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1679aa8d54'
down_revision = 'a7b9b1ccc46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Is user email (and so account) confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Is user email (and so account) confirmed')
    # ### end Alembic commands ###
