"""empty message

Revision ID: d7ba141e7cc2
Revises: 895e46e7be6e
Create Date: 2020-11-12 12:33:35.083046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7ba141e7cc2'
down_revision = '895e46e7be6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               comment='DateTime of post creation',
               existing_nullable=True)
    op.alter_column('posts', 'updated_on',
               existing_type=postgresql.TIMESTAMP(),
               comment='DateTime of post update',
               existing_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               comment='Does user has admin privileges',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               comment='Hashed user password',
               existing_nullable=False)
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(),
               comment='DateTime of registration',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Username used for authentication',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Username used for authentication',
               existing_nullable=False)
    op.alter_column('users', 'registered_on',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='DateTime of registration',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Hashed user password',
               existing_nullable=False)
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Does user has admin privileges',
               existing_nullable=False)
    op.alter_column('posts', 'updated_on',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='DateTime of post update',
               existing_nullable=True)
    op.alter_column('posts', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='DateTime of post creation',
               existing_nullable=True)
    # ### end Alembic commands ###
