"""empty message

Revision ID: dc621313db8b
Revises: 359fc77c4965
Create Date: 2020-11-12 13:01:52.144176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc621313db8b'
down_revision = '359fc77c4965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='If the post is marked for deletion then it should not be given to the client')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='If the user is marked for deletion then it should not be valid for authentification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='If the user is marked for deletion then it should not be valid for authentification')
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='If the post is marked for deletion then it should not be given to the client')
    # ### end Alembic commands ###
